# Generated by Django 5.2.17 on 2026-08-07 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapyareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('authority', models.CharField(help_text='Issuing body (e.g. ESC/EAS, ADA, ACC/AHA, KDIGO, WHO)', max_length=150)),
                ('category_name_override', models.CharField(blank=True, default='', max_length=150)),
                ('summary', models.TextField(blank=True, default='', help_text='Summary of recommendations')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guidelines/')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('document_url', models.URLField(blank=True, default='', help_text='External PDF / guideline link', max_length=500)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='guidelines_docs/')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, help_text='Primary therapy area specialty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidelines', to='therapyareas.therapyarea')),
            ],
            options={
                'verbose_name': 'Clinical Guideline',
                'verbose_name_plural': 'Clinical Guidelines',
                'ordering': ['-published_at'],
            },
        ),
    ]
