# Generated by Django 5.2.17 on 2026-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Acronym or short code (e.g. ESC, ACC, AHA, ADA)', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Full organization name (e.g. European Society of Cardiology)', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Brief summary or scope of society')),
                ('website_url', models.URLField(blank=True, default='', help_text='Official society website URL', max_length=500)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display sorting order sequence')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sub-option is displayed in website menus')),
            ],
            options={
                'verbose_name': 'Conference Guideline Society',
                'verbose_name_plural': 'Conference Guideline Societies',
                'ordering': ['order', 'code'],
            },
        ),
    ]
