# Generated by Django 5.2.17 on 2026-08-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0002_conferencesociety'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideline',
            name='guideline_type',
            field=models.CharField(choices=[('conference', 'Conference Guideline'), ('clinical_practice', 'Clinical Practice Guideline')], default='clinical_practice', help_text='Whether this is a conference congress guideline or general clinical practice guideline', max_length=30),
        ),
        migrations.AddField(
            model_name='guideline',
            name='society',
            field=models.ForeignKey(blank=True, help_text='Associated conference society issuer if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guidelines', to='guidelines.conferencesociety'),
        ),
    ]
