# Generated by Django 5.2.17 on 2026-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guidelines', '0003_guideline_guideline_type_guideline_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideline',
            name='document_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='guidelines_docs/'),
        ),
        migrations.AlterField(
            model_name='guideline',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='guidelines/'),
        ),
    ]
