# Generated by Django 5.2.17 on 2026-08-07 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapyareas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('agenda', models.JSONField(blank=True, default=list, help_text='List of agenda topics or tracks as strings')),
                ('category_name_override', models.CharField(blank=True, default='', max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(help_text='e.g. Paris, France or Boston, MA & Virtual', max_length=200)),
                ('is_virtual_available', models.BooleanField(default=True, help_text='Whether online attendance is supported')),
                ('cme_credits', models.PositiveIntegerField(blank=True, help_text='CME / CPD credit hours', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='conferences/')),
                ('image_url', models.URLField(blank=True, default='', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, help_text='Primary therapy area specialty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences', to='therapyareas.therapyarea')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
                'ordering': ['start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConferenceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('attendance_mode', models.CharField(choices=[('in_person', 'In-Person Attendance'), ('virtual', 'Virtual / Online Attendance')], default='virtual', max_length=20)),
                ('organization', models.CharField(blank=True, default='', max_length=255)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='conferences.conference')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conference_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conference Registration',
                'verbose_name_plural': 'Conference Registrations',
                'ordering': ['-registered_at'],
            },
        ),
    ]
