# Generated by Django 5.2.17 on 2026-08-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_conference_document_file_conference_document_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Conference subcategory name', max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this conference subcategory is visible on the portal')),
            ],
            options={
                'verbose_name': 'Conference Subcategory',
                'verbose_name_plural': 'Conference Subcategories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='conference',
            name='conference_category',
            field=models.ForeignKey(blank=True, help_text='Conference track / subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences', to='conferences.conferencecategory'),
        ),
    ]
