# Generated by Django 6.0.7 on 2026-09-16 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0003_conferencecategory_conference_conference_category'),
        ('guidelines', '0003_guideline_guideline_type_guideline_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='organizer',
            field=models.ForeignKey(blank=True, help_text='Organization or society hosting this conference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_conferences', to='guidelines.conferencesociety'),
        ),
    ]
