# Generated by Django 6.0.7 on 2026-09-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_conference_organizer'),
        ('therapyareas', '0003_therapysubarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Specific sub-specialty (e.g. Heart Failure)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferences', to='therapyareas.therapysubarea'),
        ),
    ]
