# Generated by Django 6.0.7 on 2026-09-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0005_conference_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='location',
            field=models.CharField(blank=True, default='', help_text='e.g. Paris, France or Boston, MA & Virtual', max_length=200),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
