# Generated by Django 5.2.17 on 2026-09-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_alter_conference_end_date_alter_conference_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='is_upcoming',
            field=models.BooleanField(default=False, help_text='Distinguishes an upcoming conference from a normal conference'),
        ),
    ]
