# Generated by Django 5.2.17 on 2026-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_conference_is_upcoming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='document_file',
            field=models.FileField(blank=True, help_text='Downloadable agenda or brochure PDF', max_length=500, null=True, upload_to='conferences_docs/'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='conferences/'),
        ),
    ]
