# Generated by Django 5.2.17 on 2026-08-07 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapyareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('summary', models.TextField(help_text='Short synopsis or abstract of the study/article')),
                ('body', models.TextField(blank=True, default='', help_text='Full article content (markdown/HTML supported)')),
                ('category_name_override', models.CharField(blank=True, default='', help_text='Optional compound category label (e.g. "Neurology & Endocrinology")', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('image_url', models.URLField(blank=True, default='', help_text='External image fallback URL', max_length=500)),
                ('reference_url', models.URLField(blank=True, default='', help_text='External reference / paper DOI URL', max_length=500)),
                ('reference_name', models.CharField(blank=True, default='', help_text='Journal name or citation text', max_length=200)),
                ('headline_tag', models.CharField(default='HEADLINE', help_text='Tag badge displayed in hero (e.g. HEADLINE, BREAKTHROUGH)', max_length=50)),
                ('is_headline', models.BooleanField(default=False, help_text='Display in top hero headline carousel')),
                ('is_published', models.BooleanField(default=True, help_text='Controls whether article is publicly visible')),
                ('read_time_minutes', models.PositiveIntegerField(default=4, help_text='Estimated read time in minutes')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, help_text='Primary therapy area specialty', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='therapyareas.therapyarea')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
