# Generated by Django 5.2.17 on 2026-08-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='document_file',
            field=models.FileField(blank=True, help_text='Downloadable PDF document', null=True, upload_to='news_docs/'),
        ),
        migrations.AddField(
            model_name='article',
            name='document_url',
            field=models.URLField(blank=True, help_text='External PDF / document link', max_length=500, null=True),
        ),
    ]
