# Generated by Django 5.2.17 on 2026-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_document_file_article_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='document_file',
            field=models.FileField(blank=True, help_text='Downloadable PDF document', max_length=500, null=True, upload_to='news_docs/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='news/'),
        ),
    ]
