# Generated by Django 5.2.17 on 2026-08-17 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=320, unique=True)),
                ('eyebrow', models.CharField(blank=True, default='GLOBAL CARDIOLOGY BULLETIN', max_length=120)),
                ('summary', models.TextField(blank=True, default='')),
                ('script', models.TextField(help_text='Narration spoken by the selected avatar')),
                ('bullet_points', models.JSONField(blank=True, default=list)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='video_bulletins/backgrounds/')),
                ('background_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('avatar', models.CharField(choices=[('female_doctor', 'Female Doctor'), ('male_doctor', 'Male Doctor'), ('female_anchor', 'Female News Anchor'), ('male_anchor', 'Male News Anchor'), ('custom', 'Custom Avatar')], default='female_doctor', max_length=30)),
                ('custom_avatar_image', models.ImageField(blank=True, null=True, upload_to='video_bulletins/avatars/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='video_bulletins/videos/')),
                ('video_url', models.URLField(blank=True, default='', max_length=500)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Video News Bulletin',
                'verbose_name_plural': 'Video News Bulletins',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
