# Generated by Django 5.2.17 on 2026-08-17 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_videobulletin'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoBulletinLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('profession', models.CharField(blank=True, default='', max_length=100)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('consent', models.BooleanField(default=True)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='cms.videobulletin')),
            ],
            options={
                'verbose_name': 'Video Bulletin Subscriber',
                'verbose_name_plural': 'Video Bulletin Subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
