# Generated by Django 5.2.17 on 2026-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_videogenerationjob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videobulletin',
            name='custom_avatar_image',
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='key_highlights',
            field=models.JSONField(blank=True, default=list, help_text='Structured cards array: [{number, category, title, summary, date_str, time_str}]'),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='previous_events',
            field=models.JSONField(blank=True, default=list, help_text='Archive events array: [{title, location_dates, bulletins_count, video_count}]'),
        ),
    ]
