# Generated by Django 5.2.17 on 2026-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_remove_videobulletin_custom_avatar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='custom_avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='video_bulletins/avatars/'),
        ),
    ]
