# Generated by Django 5.2.17 on 2026-08-17 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_videobulletin_custom_avatar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyHighlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(default='01', max_length=10)),
                ('category', models.CharField(default='HEART FAILURE', max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True, default='')),
                ('date_str', models.CharField(default='12 Aug 2026', max_length=50)),
                ('time_str', models.CharField(default='09:15', max_length=50)),
                ('article_link', models.CharField(blank=True, default='', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Key Highlight Item',
                'verbose_name_plural': 'Key Highlight Items',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
