# Generated by Django 5.2.17 on 2026-08-17 14:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_keyhighlightitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='launch_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Scheduled launch date and time for news timer countdown on home screen.'),
        ),
    ]
