# Generated by Django 5.2.17 on 2026-08-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_videobulletin_launch_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='voice_gender',
            field=models.CharField(choices=[('female', 'Female Voice'), ('male', 'Male Voice')], default='female', max_length=10),
        ),
    ]
