# Generated by Django 5.2.3 on 2026-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_videobulletin_voice_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletinlead',
            name='hospital_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
