# Generated by Django 5.2.17 on 2026-08-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_videobulletinlead_hospital_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='promo_banner_image',
            field=models.ImageField(blank=True, help_text='Optional banner image specifically for homepage news promo card', null=True, upload_to='video_bulletins/banners/'),
        ),
    ]
