# Generated by Django 5.2.3 on 2026-08-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_videobulletin_promo_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='event_title',
            field=models.CharField(blank=True, default='', help_text='Custom event title to group multiple sequential video clips (e.g. ESC Congress 2026)', max_length=300),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='parent_event',
            field=models.ForeignKey(blank=True, help_text='Parent event bulletin if this is a secondary update video clip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_clips', to='cms.videobulletin'),
        ),
    ]
