# Generated by Django 5.2.3 on 2026-08-24 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_videobulletin_event_title_videobulletin_parent_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='loop_start_clip',
            field=models.ForeignKey(blank=True, help_text='Target clip to loop back to when playlist finishes (e.g. Video #5)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loop_children', to='cms.videobulletin'),
        ),
    ]
