# Generated by Django 5.2.3 on 2026-08-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_videobulletin_loop_start_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='avatar_position',
            field=models.CharField(choices=[('left', 'Left Anchor'), ('center', 'Center Anchor'), ('right', 'Right Anchor')], default='left', help_text='Presenter placement position inside newsroom background', max_length=20),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='avatar_scale',
            field=models.CharField(choices=[('standard', 'Standard (100%)'), ('medium', 'Medium (120%)'), ('large', 'Large Broadcast (140%)')], default='medium', help_text='Presenter display size scale', max_length=20),
        ),
    ]
