# Generated by Django 5.2.3 on 2026-08-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_videobulletin_avatar_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='avatar_x_offset',
            field=models.FloatField(default=4.0, help_text='Presenter horizontal offset percentage (0 to 80%)'),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='avatar_y_offset',
            field=models.FloatField(default=0.0, help_text='Presenter vertical offset percentage (-10 to 30%)'),
        ),
    ]
