# Generated by Django 5.2.3 on 2026-08-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_videobulletin_avatar_x_offset_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='show_countdown_timer',
            field=models.BooleanField(default=True, help_text='Show countdown timer below banner on homepage'),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='event_start_datetime',
            field=models.DateTimeField(blank=True, help_text='Event start date and time for countdown timer', null=True),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='event_timer_label',
            field=models.CharField(blank=True, default='', help_text='Custom label for event countdown timer (e.g. ESC Congress 2026 Starts In)', max_length=200),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='schedule_start_datetime',
            field=models.DateTimeField(blank=True, help_text='Schedule when this banner should start displaying on homepage', null=True),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='schedule_end_datetime',
            field=models.DateTimeField(blank=True, help_text='Schedule when this banner should stop displaying on homepage', null=True),
        ),
    ]
