# Generated by Django 5.2.17 on 2026-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_videobulletin_event_start_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSectionVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_key', models.CharField(help_text="Unique programmatic identifier (e.g. 'news_articles', 'conferences', 'education')", max_length=60, unique=True)),
                ('title', models.CharField(help_text='Human-readable title displayed in admin CMS', max_length=150)),
                ('description', models.TextField(blank=True, default='', help_text='Explanation of where this section appears and what content it displays')),
                ('location', models.CharField(choices=[('homepage_hero', 'Homepage Hero & Banner'), ('homepage_grid', 'Homepage Dashboard Grid'), ('showcase', 'Full-Width Showcase Section'), ('navigation', 'Main Header Navigation'), ('footer', 'Footer Area')], default='homepage_grid', help_text='Visual region where this section is rendered', max_length=30)),
                ('icon', models.CharField(default='Layers', help_text='Lucide-react icon component name', max_length=60)),
                ('is_enabled', models.BooleanField(default=True, help_text='Master toggle: If False, the section is completely hidden from public visitors')),
                ('auto_hide_if_empty', models.BooleanField(default=True, help_text='Automatically suppress section on public portal if published item count is 0')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sorting order in CMS controls and frontend layout')),
                ('custom_metadata', models.JSONField(blank=True, default=dict, help_text='Extensible parameters (e.g. max_items, custom_cta, subtitle)')),
            ],
            options={
                'verbose_name': 'Content Section Visibility',
                'verbose_name_plural': 'Content Section Visibility Controls',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
