# Generated by Django 5.2.17 on 2026-08-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_contentsectionvisibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='esc_guidelines',
            field=models.JSONField(blank=True, default=list, help_text='List of guideline links. Format: [{title, link_url, is_pdf}]'),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='esc_guidelines_badge_text',
            field=models.CharField(blank=True, default='New', help_text="Text to show on the trigger badge (e.g., 'New')", max_length=150),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='show_esc_guidelines_popup',
            field=models.BooleanField(default=False, help_text='Show a popup below the promo banner'),
        ),
    ]
