# Generated by Django 5.2.17 on 2026-08-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_videobulletin_esc_guidelines_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videobulletin',
            name='esc_guidelines',
        ),
        migrations.RemoveField(
            model_name='videobulletin',
            name='esc_guidelines_badge_text',
        ),
        migrations.RemoveField(
            model_name='videobulletin',
            name='show_esc_guidelines_popup',
        ),
        migrations.AlterField(
            model_name='videobulletin',
            name='eyebrow',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='videobulletinlead',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
