# Generated by Django 5.2.17 on 2026-09-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_remove_videobulletin_esc_guidelines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videobulletin',
            name='promo_headline',
            field=models.TextField(blank=True, default='Cardiovascular knowledge,\ndelivered with clinical precision', help_text='Large headline text shown on the left of the homepage banner'),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='promo_kicker',
            field=models.CharField(blank=True, default='Scientice medical newsroom', help_text='Small top text above the main banner headline', max_length=150),
        ),
    ]
