# Generated by Django 5.2.3 on 2026-09-28 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_videobulletin_promo_headline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresenterAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name (e.g. Dr. Sarah - Cardiologist)', max_length=150)),
                ('image', models.ImageField(help_text='Presenter portrait cutout image (PNG/JPG)', upload_to='avatars/presets/')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', help_text='Avatar gender (automatically controls AI voice generation)', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Toggle active/deactivated status')),
            ],
            options={
                'verbose_name': 'Presenter Avatar Preset',
                'verbose_name_plural': 'Presenter Avatar Presets',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PresenterBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name (e.g. Modern Cardiology Studio)', max_length=150)),
                ('image', models.ImageField(help_text='Studio background image (16:9 1920x1080 recommended)', upload_to='backgrounds/presets/')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Toggle active/deactivated status')),
            ],
            options={
                'verbose_name': 'Presenter Background Preset',
                'verbose_name_plural': 'Presenter Background Presets',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='avatar_preset',
            field=models.ForeignKey(blank=True, help_text='Preset avatar from presenter library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='cms.presenteravatar'),
        ),
        migrations.AddField(
            model_name='videobulletin',
            name='background_preset',
            field=models.ForeignKey(blank=True, help_text='Preset background image from studio library', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='cms.presenterbackground'),
        ),
    ]
