# Generated by Django 5.2.17 on 2026-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_presenteravatar_presenterbackground_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenteravatar',
            name='image',
            field=models.ImageField(help_text='Presenter portrait cutout image (PNG/JPG)', max_length=500, upload_to='avatars/presets/'),
        ),
        migrations.AlterField(
            model_name='presenterbackground',
            name='image',
            field=models.ImageField(help_text='Studio background image (16:9 1920x1080 recommended)', max_length=500, upload_to='backgrounds/presets/'),
        ),
        migrations.AlterField(
            model_name='videobulletin',
            name='avatar_scale',
            field=models.CharField(blank=True, default='100', help_text='Presenter display size scale percentage or preset name', max_length=50),
        ),
        migrations.AlterField(
            model_name='videobulletin',
            name='background_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='video_bulletins/backgrounds/'),
        ),
        migrations.AlterField(
            model_name='videobulletin',
            name='custom_avatar_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='video_bulletins/avatars/'),
        ),
        migrations.AlterField(
            model_name='videobulletin',
            name='promo_banner_image',
            field=models.ImageField(blank=True, help_text='Optional banner image specifically for homepage news promo card', max_length=500, null=True, upload_to='video_bulletins/banners/'),
        ),
        migrations.AlterField(
            model_name='videobulletin',
            name='video_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='video_bulletins/videos/'),
        ),
        migrations.AlterField(
            model_name='videogenerationjob',
            name='output_file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='video_bulletins/generated/'),
        ),
    ]
