# Generated by Django 5.2.17 on 2026-08-07 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Infographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('tag', models.CharField(default='INFOGRAPHIC', help_text='Display badge/tag (e.g. INFOGRAPHIC, CLINICAL PATHWAY)', max_length=60)),
                ('subtitle', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='Clinical Guidelines', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='infographics/')),
                ('image_url', models.URLField(blank=True, default='', help_text='External infographic image URL', max_length=500)),
                ('reference', models.CharField(blank=True, default='', max_length=300)),
                ('reference_url', models.URLField(blank=True, default='', max_length=500)),
                ('quote', models.TextField(blank=True, default='', help_text='Key highlight quote')),
                ('alert', models.TextField(blank=True, default='', help_text='Critical clinical alert or warning box')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Infographic',
                'verbose_name_plural': 'Infographics',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InfographicPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='Step/point index (e.g. 1, 2, 3)')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('infographic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='infographics.infographic')),
            ],
            options={
                'verbose_name': 'Infographic Key Point',
                'verbose_name_plural': 'Infographic Key Points',
                'ordering': ['order', 'id'],
            },
        ),
    ]
