# Generated by Django 6.0.7 on 2026-09-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0002_infographic_document_file_infographic_document_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='infographic',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Brief description or summary'),
        ),
    ]
