# Generated by Django 5.2.17 on 2026-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infographics', '0003_infographic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infographic',
            name='document_file',
            field=models.FileField(blank=True, help_text='Downloadable PDF version', max_length=500, null=True, upload_to='infographics_docs/'),
        ),
        migrations.AlterField(
            model_name='infographic',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='infographics/'),
        ),
    ]
