# Generated by Django 5.2.17 on 2026-08-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TherapyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Therapy area or medical specialty name', max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('icon', models.CharField(default='Stethoscope', help_text='lucide-react icon component name (e.g. Heart, Stethoscope, Brain)', max_length=60)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display ordering index')),
            ],
            options={
                'verbose_name': 'Therapy Area',
                'verbose_name_plural': 'Therapy Areas',
                'ordering': ['order', 'name'],
            },
        ),
    ]
