# Generated by Django 5.2.17 on 2026-08-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapyareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapyarea',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Controls whether this therapy specialty is active and visible across portal menus and widgets'),
        ),
    ]
