# Generated by Django 6.0.7 on 2026-09-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapyareas', '0002_therapyarea_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapySubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Sub-specialty name (e.g. Heart Failure)', max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display ordering index')),
                ('is_active', models.BooleanField(default=True, help_text='Controls whether this sub-specialty is visible')),
                ('therapy_area', models.ForeignKey(help_text='Parent therapy area specialty', on_delete=django.db.models.deletion.CASCADE, related_name='sub_areas', to='therapyareas.therapyarea')),
            ],
            options={
                'verbose_name': 'Therapy Sub-Area',
                'verbose_name_plural': 'Therapy Sub-Areas',
                'ordering': ['therapy_area', 'order', 'name'],
                'unique_together': {('therapy_area', 'name')},
            },
        ),
    ]
