# Generated by Django 5.2.17 on 2026-08-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='General Inquiry', max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False, help_text='Mark message as read/reviewed by editorial staff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inbound Contact Message',
                'verbose_name_plural': 'Inbound Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(default='+1 (800) 555-0199', max_length=60)),
                ('email', models.EmailField(default='contact@scientice.org', max_length=254)),
                ('address', models.TextField(default='Scientice Medical Institute, 500 Healthcare Blvd, Suite 400, Boston, MA 02115')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/scientice')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/scientice')),
                ('website_url', models.URLField(blank=True, default='https://scientice.org')),
            ],
            options={
                'verbose_name': 'Site Contact Information',
                'verbose_name_plural': 'Site Contact Information',
            },
        ),
    ]
