# Generated by Django 5.2.17 on 2026-08-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='address',
            field=models.TextField(blank=True, default='Scientice Medical Institute, 500 Healthcare Blvd, Suite 400, Boston, MA 02115', null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='email',
            field=models.EmailField(blank=True, default='contact@scientice.org', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/scientice', null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/scientice', null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='phone',
            field=models.CharField(blank=True, default='+1 (800) 555-0199', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='website_url',
            field=models.URLField(blank=True, default='https://scientice.org', null=True),
        ),
    ]
