# Generated by Django 5.2.17 on 2026-08-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontact', '0002_alter_siteinfo_address_alter_siteinfo_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='show_conferences_widget',
            field=models.BooleanField(default=True, help_text='Show Conferences widget in dashboard grid'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_education_widget',
            field=models.BooleanField(default=False, help_text='Show Education widget in dashboard grid'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_guidelines_showcase',
            field=models.BooleanField(default=True, help_text='Show Featured Guidelines Showcase Section below Hero Banner'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_guidelines_widget',
            field=models.BooleanField(default=True, help_text='Show Guidelines widget in dashboard grid'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_headline_slider',
            field=models.BooleanField(default=True, help_text='Show Headline Articles Slider & Infographics'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_hero_banner',
            field=models.BooleanField(default=True, help_text='Show Top Event Hero Promo Banner on Homepage'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_news_widget',
            field=models.BooleanField(default=True, help_text='Show Latest News widget in dashboard grid'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_therapy_areas_widget',
            field=models.BooleanField(default=True, help_text='Show Therapy Areas widget in dashboard grid'),
        ),
    ]
