# Generated by Django 5.2.17 on 2026-08-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontact', '0003_siteinfo_show_conferences_widget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='after_event_guidelines_badge_text',
            field=models.CharField(blank=True, default='New', help_text="Text to show on the trigger badge (e.g., 'New')", max_length=150),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='after_event_guidelines_list',
            field=models.JSONField(blank=True, default=list, help_text='List of guideline links. Format: [{title, link_url, is_pdf}]'),
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='show_after_event_guidelines',
            field=models.BooleanField(default=False, help_text='Show a popup containing guidelines after the hero event banner'),
        ),
    ]
