# Generated by Django 5.2.17 on 2026-08-07 06:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('patient', 'Patient Education'), ('medical', 'Medical Education'), ('cme', 'CME & Guidelines')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='BookOpen', help_text='lucide-react icon name (e.g. Users, GraduationCap, FileCheck)', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Education Category',
                'verbose_name_plural': 'Education Categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EducationResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='', help_text='Brief summary or resource overview')),
                ('body', models.TextField(blank=True, default='', help_text='Full markdown or HTML content')),
                ('icon', models.CharField(blank=True, default='', max_length=60)),
                ('file', models.FileField(blank=True, help_text='Downloadable PDF or presentation', null=True, upload_to='education_docs/')),
                ('external_url', models.URLField(blank=True, default='', help_text='Link to external course or webinar', max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='education.educationcategory')),
            ],
            options={
                'verbose_name': 'Education Resource',
                'verbose_name_plural': 'Education Resources',
                'ordering': ['-published_at'],
            },
        ),
    ]
