# Generated by Django 6.0.7 on 2026-09-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_educationcategory_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationresource',
            name='image',
            field=models.ImageField(blank=True, help_text='Thumbnail banner image', null=True, upload_to='education/'),
        ),
        migrations.AddField(
            model_name='educationresource',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='External image fallback URL', max_length=500),
        ),
    ]
