# Generated by Django 5.2.17 on 2026-10-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_educationresource_image_educationresource_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationresource',
            name='file',
            field=models.FileField(blank=True, help_text='Downloadable PDF or presentation', max_length=500, null=True, upload_to='education_docs/'),
        ),
        migrations.AlterField(
            model_name='educationresource',
            name='image',
            field=models.ImageField(blank=True, help_text='Thumbnail banner image', max_length=500, null=True, upload_to='education/'),
        ),
    ]
